fix: disable implementado nos botoes e pequenos ajustes nas requisicoes
lahr-victor/linkr pull request #7
Opened 2023-06-01 22:18 UTC by sanzinnn

dados do usuario tambem foram adicionados no context. imagem do usuario inserida no src do header

2023-06-01 22:51 UTC, MatheusW166 approved these changes

2023-06-01 23:00 UTC, MatheusW166 requested changes

2023-06-01 23:00 UTC, MatheusW166 commented on src/components/Header/index.jsx
Na linha 15, trocar:

const promise = client.delete(`${process.env.REACT_APP_API_URL}/log-out`, {});

para:

const promise = client.delete('/log-out', {});

2023-06-01 23:00 UTC, MatheusW166 commented on src/pages/SignIn.jsx
Na linha 32, trocar:

const promise = client.post(process.env.REACT_APP_API_URL, signInTemplate);

para:

const promise = client.post('/', signInTemplate);

2023-06-01 23:00 UTC, MatheusW166 commented on src/pages/SignUpPage.jsx
Na linha 34, trocar:

const promise = client.post(`${process.env.REACT_APP_API_URL}/sign-up`, templateSignUp);

para:

const promise = client.post(`/sign-up`, templateSignUp);

2023-06-02 01:21 UTC, sanzinnn reviewed
urls desnecessarias apagadas

2023-06-02 01:46 UTC, MatheusW166 approved these changes

2023-06-02 10:41 UTC, merged